#[derive(Clone, Debug)]
pub enum Token {
    Number(f64, usize, usize),
    Identifier(String, usize, usize),
    String(String, usize, usize),
    Bool(bool, usize, usize),
    OpenParenthesis(usize, usize),
    CloseParenthesis(usize, usize),
    OpenBrace(usize, usize),
    CloseBrace(usize, usize),
    OpenBracket(usize, usize),
    CloseBracket(usize, usize),
    Comma(usize, usize),
    Plus(usize, usize),
    Minus(usize, usize),
    Multiply(usize, usize),
    Divide(usize, usize),
    Assign(usize, usize),
    Greater(usize, usize),
    Less(usize, usize),
    Equal(usize,usize),
    GreaterEqual(usize, usize),
    LessEqual(usize, usize),
    NotEqual(usize, usize),
    If(usize, usize),
    Else(usize, usize),
    While(usize, usize),
    Loop(usize, usize),
    Break(usize, usize),
    Continue(usize, usize),
    Function(usize, usize),
    Return(usize, usize),
}

impl Token {
    pub fn info(&self) -> (usize, usize) {
        match self {
            Token::Number(_, start, end) => (*start, *end),
            Token::Identifier(_, start, end) => (*start, *end),
            Token::String(_, start, end) => (*start, *end),
            Token::Bool(_, start, end) => (*start, *end),
            Token::OpenParenthesis(start, end) => (*start, *end),
            Token::CloseParenthesis(start, end) => (*start, *end),
            Token::OpenBrace(start, end) => (*start, *end),
            Token::CloseBrace(start, end) => (*start, *end),
            Token::OpenBracket(start, end) => (*start, *end),
            Token::CloseBracket(start, end) => (*start, *end),
            Token::Comma(start, end) => (*start, *end),
            Token::Plus(start, end) => (*start, *end),
            Token::Minus(start, end) => (*start, *end),
            Token::Multiply(start, end) => (*start, *end),
            Token::Divide(start, end) => (*start, *end),
            Token::Assign(start, end) => (*start, *end),
            Token::Greater(start, end) => (*start, *end),
            Token::Less(start, end) => (*start, *end),
            Token::Equal(start, end) => (*start, *end),
            Token::GreaterEqual(start, end) => (*start, *end),
            Token::LessEqual(start, end) => (*start, *end),
            Token::NotEqual(start, end) => (*start, *end),
            Token::If(start, end) => (*start, *end),
            Token::Else(start, end) => (*start, *end),
            Token::While(start, end) => (*start, *end),
            Token::Loop(start, end) => (*start, *end),
            Token::Break(start, end) => (*start, *end),
            Token::Continue(start, end) => (*start, *end),
            Token::Function(start, end) => (*start, *end),
            Token::Return(start, end) => (*start, *end),
        }
    }

    pub fn value(&self) -> String {
        match self {
            Token::Number(value, _ ,_) => value.to_string(),
            Token::Identifier(value, _, _) => value.clone(),
            Token::String(value, _, _) => value.clone(),
            Token::Bool(value, _, _) => value.to_string(),
            Token::OpenParenthesis(_, _) => String::from("("),
            Token::CloseParenthesis(_, _) => String::from(")"),
            Token::OpenBrace(_, _) => String::from("{"),
            Token::CloseBrace(_, _) => String::from("}"),
            Token::OpenBracket(_, _) => String::from("["),
            Token::CloseBracket(_, _) => String::from("]"),
            Token::Comma(_, _) => String::from(","),
            Token::Plus(_, _) => String::from("+"),
            Token::Minus(_, _) => String::from("-"),
            Token::Multiply(_, _) => String::from("*"),
            Token::Divide(_, _) => String::from("/"),
            Token::Assign(_, _) => String::from("="),
            Token::Greater(_, _) => String::from(">"),
            Token::Less(_, _) => String::from("<"),
            Token::Equal(_, _) => String::from("=="),
            Token::GreaterEqual(_, _) => String::from(">="),
            Token::LessEqual(_, _) => String::from("<="),
            Token::NotEqual(_, _) => String::from("!="),
            Token::If(_, _) => String::from("if"),
            Token::Else(_, _) => String::from("else"),
            Token::While(_, _) => String::from("while"),
            Token::Loop(_, _) => String::from("loop"),
            Token::Break(_, _) => String::from("break"),
            Token::Continue(_, _) => String::from("continue"),
            Token::Function(_, _) => String::from("function"),
            Token::Return(_, _) => String::from("return"),
        }
    }
}